using ProductCatalogService.DTO;
using ProductCatalogService.Models;

namespace ProductCatalogService.Mapper
{
    public static class CreateProductMapper
    {
        public static Product ToEntity(CreateProductDto dto)
        {
            return new Product
            {
                // Id will be generated by DB, so we don't set it
                Name = dto.Name
            };
        }

        public static CreateProductDto ToDto(Product product)
        {
            return new CreateProductDto
            {
                Name = product.Name
            };
        }
    }
}
